language: android
android:
  components:
    - tools
    - platform-tools
    - build-tool-23.0.3
    - android-24
    - extra-google-google_play_services
    - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - java -version
  - ./gradlew --version
  - ./gradlew clean build --debug
notifications:
  email: false