language: android
android:
  components:
    - tools
    - platform-tools
    - build-tool-23.0.2
    - android-M
    - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew --version
  - ./gradlew clean build --debug
notifications:
  email: false