language: android
jdk: oraclejdk8
#sudo: required

android:
  components:
    - tools
    - platform-tools

# The BuildTools version used by your project
    - build-tools-23.0.3

# The SDK version used to compile your project
    - android-24
    - android-25

    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
#    - oraclejdk8
#install: true
before_install:
  - chmod +x gradlew
#before_script:
#  - echo y | android update sdk --no-ui --filter build-tools-24.0.0,android-24,build-tools-23.0.3,android-23,extra-android-m2repository
script:
#  - sudo apt-get update && sudo apt-get install oracle-java8-installer
#  - java -version
#  - ./gradlew --version
  - ./gradlew clean build
notifications:
  email: false
  slack:
    secure: vmEm/RbQLTBMGfbLt0kAokmJ3OyvNIWA/cWEuya9OH4gFmdnv5lMuu4JO0dY+LwSM0p3vk2YCHcoSzEb34Laj4QtG8d7vEePo0OlJMjjjWlYH3y4vE+BbPOxH9sZ7cqC4dFgMRLKDfLmbhxXnUeTw40OHeOxqs036yE30gGZ4rVUYqBGmk+ehv0FxA75XCuFy31fP9UYdvGq4BLROrfnbrshbMZVy0sH9iR2Nnyo8OQtRQmVS+FWeQGilOh7yzXU6dSWAj//ltwSCWyDpsXAGgwyX3tU0lCFlU9vQxPVtNT/hJIgjXQa+uktyztley6cn+OuJL7sqCZTe+H7a2Uec9vBFmlF8UolJ6d1woj/SctzYjLDBj1i3j3Yw5SfJWTMSyUI+1qF/NfVCoeXeW8B2FZzckfPIPMcLB/A6MlAronnEx9QHrYSEcuQXB/m3PWOOtIjxZzO1SMe0p2zaHWIQGNanvND2+SLOT/ZrynleBx45VTc6T6xfmaHgueRnO9umBfLa51nP0cg6AmOqxH8L2/YgN1MAeSDpK0DJwAYlK9X9S6f5+7aI2e4g25bPo1r14QF383K1ypWunT+ZATHRZ8yh8mnGpsEt3XAQNrd7QzxIBrJbm4v/qJwaxc6HE6KkTf8a8L46iUORhy6L3xeMU6XXAIpjuuow29TThNCm+Q=
